### ISSUE TITLE
venv_update: ImportError: cannot import name basecommand

### ISSUE THREAD

**Issue by seanh** [tox-dev/tox-pip-extensions#17]
We're trying to add tox-pip-extensions and the venv_update extension to our project, but it's causing an `ImportError: cannot import name basecommand` crash when we run tox.

Here's [our PR that adds tox-pip-extensions and venv_update](https://github.com/hypothesis/h/pull/5349). We're pinning to `tox===3.3.0` to work around <https://github.com/tox-dev/tox-pip-extensions/issues/16> (tox-pip-extensions doesn't seem to work with tox 3.4.0) but then we're running in to this second problem.

Here's [the output from running our tests](https://travis-ci.org/hypothesis/h/jobs/437718945). They're failing in the dependency install phase. Traceback:

```
$ tox
py27 create: /home/travis/build/[secure]/h/.tox/py27
py27 bootstrap: venv-update>=2.1.3
py27 installdeps: coverage,mock,pytest,[secure],factory-boy,-rrequirements.txt
ERROR: invocation failed (exit code 1), logfile: /home/travis/build/[secure]/h/.tox/py27/log/py27-2.log
ERROR: actionid: py27
msg: getenv
cmdargs: ['/home/travis/build/[secure]/h/.tox/py27/bin/pip-faster', u'install', 'coverage', 'mock', 'pytest', '[secure]', 'factory-boy', '-rrequirements.txt', 'venv-update>=2.1.3']
Traceback (most recent call last):
  File "/home/travis/build/[secure]/h/.tox/py27/bin/pip-faster", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/[secure]/h/.tox/py27/lib/python2.7/site-packages/pip_faster.py", line 465, in main
    with pipfaster_packagefinder():
  File "/home/travis/build/[secure]/h/.tox/py27/lib/python2.7/site-packages/pip_faster.py", line 448, in pipfaster_packagefinder
    from pip._internal import basecommand
ImportError: cannot import name basecommand
ERROR: could not install deps [coverage, mock, pytest, [secure], factory-boy, -rrequirements.txt]; v = InvocationError('/home/travis/build/[secure]/h/.tox/py27/bin/pip-faster install coverage mock pytest [secure] factory-boy -rrequirements.txt venv-update>=2.1.3 (see /home/travis/build/[secure]/h/.tox/py27/log/py27-2.log)', 1)
```

**Comment by asottile** [comment]
hmmm, this looks like a problem with venv-update itself (probably pip 18.x breaks venv-update)

For me it works, but that's probably because I have `tox-virtualenv-no-download` preventing pip from updating out from under me:

```console
h$ tox -e py27 --notest
py27 create: /tmp/h/.tox/py27
py27 bootstrap: venv-update>=2.1.3
py27 installdeps: coverage,mock,pytest,hypothesis,factory-boy,-rrequirements.txt
py27 installed: You are using pip version 10.0.1, however version 18.1 is available.,You should consider upgrading via the 'pip install --upgrade pip' command.,alembic==0.9.7,amqp==2.2.2,atomicwrites==1.2.1,attrs==18.2.0,backports.functools-lru-cache==1.2.1,bcrypt==3.1.3,billiard==3.5.0.3,bleach==2.1.3,celery==4.2.1,certifi==2016.2.28,cffi==1.7.0,Chameleon==2.24,click==6.6,colander==1.3.1,contextlib2==0.5.4,coverage==4.5.1,deform==0.9.9,deform-jinja2==0.5,elasticsearch==6.2.0,elasticsearch-dsl==6.1.0,enum34==1.1.6,factory-boy==2.11.1,Faker==0.9.1,funcsigs==1.0.2,functools32==3.2.3.post2,gevent==1.3.5,greenlet==0.4.13,gunicorn==19.9.0,hkdf==0.0.3,html5lib==0.999999999,hypothesis==3.74.2,ipaddress==1.0.18,iso8601==0.1.11,itsdangerous==0.24,Jinja2==2.10,jsonpointer==1.0,jsonschema==2.5.1,kombu==4.2.1,Mako==1.0.4,MarkupSafe==0.23,mistune==0.8.3,mock==2.0.0,more-itertools==4.3.0,newrelic==4.2.0.100,oauthlib==2.0.2,passlib==1.7.1,PasteDeploy==1.5.2,pathlib2==2.3.2,pbr==4.3.0,peppercorn==0.5,pluggy==0.7.1,psycogreen==1.0,psycopg2==2.7.3.2,py==1.6.0,pycparser==2.14,PyJWT==1.5.3,pyparsing==2.1.10,pyramid==1.7.3,pyramid-authsanity==1.0.0,pyramid-jinja2==2.6.2,pyramid-layout==1.0,pyramid-mailer==0.15.1,pyramid-services==0.4,pyramid-tm==1.1.1,pytest==3.8.2,python-dateutil==2.5.3,python-editor==1.0.1,python-slugify==1.1.4,pytz==2016.6.1,raven==6.0.0,repoze.lru==0.6,repoze.sendmail==4.3,requests==2.13.0,requests-aws4auth==0.9,scandir==1.9.0,six==1.10.0,SQLAlchemy==1.1.4,statsd==3.2.1,text-unidecode==1.2,transaction==2.1.2,translationstring==1.3,Unidecode==0.4.19,urllib3==1.22,venusian==1.0,venv-update==3.1.0,vine==1.1.4,webencodings==0.5.1,WebOb==1.6.1,ws4py==0.4.2,wsaccel==0.6.2,zope.deprecation==4.1.2,zope.interface==4.3.2,zope.sqlalchemy==1.0
___________________________________ summary ____________________________________
  py27: skipped tests
  congratulations :)

h$ tox --version
3.3.0 imported from /home/asottile/opt/venv/lib/python3.6/site-packages/tox/__init__.py
registered plugins:
    tox-virtualenv-no-download-1.0.2 at /home/asottile/opt/venv/lib/python3.6/site-packages/tox_virtualenv_no_download.py
    tox-pip-extensions-1.3.0 at /home/asottile/opt/venv/lib/python3.6/site-packages/tox_pip_extensions.py
```

**Comment by asottile** [comment]
I've opened an upstream issue, follow along there!

https://github.com/Yelp/venv-update/issues/214

**Comment by seanh** [comment]
Thanks! I'm following
